#
# Runs when a pull request into dev branch has been closed with a merge.
#
name: pr-to-dev-closed
run-name: "${{ github.workflow }}: ${{ github.ref_name }} / ${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    # Using branches and paths filters, requires both filters to be satisfied.
    branches:
      - 'dev'
    paths:
      - 'assets/**'
      - 'src/**'
      - 'tests/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Trunk.toml'
      - 'trunk-post-build.sh'
      - '.github/workflows/ev_pr-to-dev-closed.yml'
      - '.github/workflows/wf_full.yml'

defaults:
  run:
    shell: bash

jobs:
  cargo-fetch:
    uses: polarlabs/factory/.github/workflows/cargo-dep-cache.yml@feat/cargo-dep-cache

  wf_full:
    uses: polarlabs/kodiak-web-client/.github/workflows/wf_full.yml@dev
    needs: [ cargo-fetch ]
    strategy:
      matrix:
        profiles: [ dev ]
      fail-fast: false
    with:
      ARTIFACT_NAME: "dist.tar.gz"
      DEPS_CACHE_KEY: ${{ needs.cargo-fetch.outputs.CACHE_KEY }}
      RELEASE_TAG: "${{ github.ref_name }}/latest"
      PROFILE: ${{ matrix.profiles }}
    secrets: inherit
