name: pr-to-dev
run-name: "${{ github.workflow }}: ${{ github.base_ref }} / ${{ github.run_number }}.${{ github.run_attempt }}"

on:
  pull_request:
    # Using branches and paths filters, requires both filters to be satisfied.
    branches:
      - 'dev'
    paths:
      - 'assets/**'
      - 'src/**'
      - 'tests/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Trunk.toml'
      - 'trunk-post-build.sh'
      - '.github/workflows/ev_pr-to-dev.yml'
      - '.github/workflows/wf_full.yml'

defaults:
  run:
    shell: bash

jobs:
  cargo-fetch:
    uses: polarlabs/factory/.github/workflows/cargo-dep-cache.yml@v/4.0.0

  wf_build-test:
    uses: polarlabs/kodiak-web-client/.github/workflows/wf_build-test.yml@dev
    needs: [ cargo-fetch ]
    strategy:
      matrix:
        profiles: [ dev ]
      fail-fast: false
    with:
      ARTIFACT_NAME: "dist.tar.gz"
      DEPS_CACHE_KEY: ${{ needs.cargo-fetch.outputs.CACHE_KEY }}
      PROFILE: ${{ matrix.profiles }}
    secrets: inherit
